'use client'

import { useEffect } from 'react'
import './TermsModal.css'

export default function TermsModal({ isOpen, onClose }) {
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = 'unset'
    }
    return () => {
      document.body.style.overflow = 'unset'
    }
  }, [isOpen])

  if (!isOpen) return null

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </button>
        <div className="modal-body">
          <h2 className="modal-title">Terms of Service</h2>
          <p className="modal-date"><strong>Last Updated: March 24, 2024</strong></p>
          
          <p>These terms of service (the "Terms of Service") constitute a legal agreement between you and SoundCheck Capital, a Delaware limited liability company (the "Company" or "SoundCheck"). As used in these Terms of Service, the words "you" and "your" refer to you, the user of the Company's website, device, or applications, as the party agreeing to these Terms of Service. The words "we", "us", "our" and any other variation thereof refer to the Company and its affiliates, including without limitation its subsidiaries, and their respective successors and assigns. Any reference to "Company" in this document includes our affiliates, directors, officers, members, managers, equity holders, employees, contractors, owners, agents, licensors, or licensees. As used in these Terms of Service, the term "Site(s)" includes all websites and all devices or applications that we operate, pages within each such website, device, or application, any equivalent, mirror, replacement, substitute, or backup website, device, or application, and pages that are associated with each such website, device, or application. The use of the word "including" in these Terms of Service to refer to specific examples will be construed to mean "including, without limitation" or "including but not limited to" and will not be construed to mean that the examples given are an exclusive or exhaustive list of the topics covered.</p>

          <h3>Acceptance of Terms</h3>
          <p>PLEASE READ THESE TERMS OF SERVICE CAREFULLY. BY ACCESSING OR USING THE SITE OR THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD AND AGREE TO BE BOUND BY THE TERMS OF SERVICE AND THE COMPANY'S PRIVACY POLICY, AS MAY BE AMENDED AND UPDATED FROM TIME TO TIME. IF YOU ARE ENTERING INTO THIS TERMS OF SERVICE ON BEHALF OF A COMPANY, BUSINESS OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE AUTHORITY TO BIND SUCH ENTITY AND AFFILIATES TO THIS TERMS OF SERVICE AND THE COMPANY'S PRIVACY POLICY, IN WHICH CASE THE TERMS "YOU" OR "YOUR" SHALL REFER TO SUCH ENTITY AND ITS AFFILIATES. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT AGREE TO BE BOUND BY THESE TERMS OF SERVICE AND THE COMPANY'S PRIVACY POLICY, YOU MAY NOT ACCESS OR USE THE SITE OR THE SERVICES. You may not use the Site or the Services (as defined below in Section 6), or accept these Terms of Service, if (a) you are not of legal age to form a binding contract with the Company; or (b) you are prohibited by law or regulation from receiving or using the Services.</p>
          <p>We reserve the right, at our discretion, to make changes to the Terms of Service from time to time without notice, so please review it frequently. You may review updates to our Terms of Service at any time via links on www.soundcheckcapital.com. You agree to accept electronic communications and/or postings of revised versions of the Terms of Service on www.soundcheckcapital.com and agree that such electronic communications or postings constitute notice to you of the revised version of the Terms of Service. Changes take effect immediately upon posting. Your continued use of the Services after any changes or revisions to the Terms of Service shall indicate your agreement with the terms of such revised and/or modified Terms of Service.</p>
          <p>In addition to these Terms of Service, you may enter into other agreements with us or others that will govern your use of the Service or related financing transactions, including, without limitation, the Master Advance Agreement, Advance Agreement, Guaranty, and other agreements executed between you and the Company or its affiliates, if executed (collectively, the "Advance Agreements"). THESE TERMS OF SERVICE DO NOT COVER OR GOVERN THE TERMS OF FINANCING TRANSACTION BETWEEN YOU AND THE COMPANY'S AFFILIATES, UNLESS OTHERWISE STATED HEREIN. If there is any conflict between these Terms of Service and any executed Advance Agreement, the Advance Agreement shall take precedence in relation to the specific aspects of the Service to which it applies. If an affiliate of the Company decides to enter into an Advance Agreement with you (in its sole and absolute discretion), then the terms of such financing transaction will be governed by the separate Advance Agreement.</p>

          <h3>Privacy and your Personal Information</h3>
          <p>For information about the Company's data protection and privacy practices, please read the Company's Privacy Policy (<a href="https://www.soundcheckcapital.com/privacy-policy/" target="_blank" rel="noopener noreferrer">https://www.soundcheckcapital.com/privacy-policy/</a>), which is hereby incorporated into this Terms of Service. The Privacy Policy explains how the Company treats your personal information when you use the Service. The policy may be updated from time to time at our discretion. Changes will be effective upon posting to the Site.</p>

          <h3>Registration Information</h3>
          <p>You agree and understand that you are responsible for maintaining the confidentiality of the combination of your Login ID and password, which together allow you to access the Services. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. If you believe that such Login ID and password, together with any account information you provide or a device that you use to access any Site has been lost or stolen, that someone is using your account without your permission, or that an unauthorized transaction has occurred, you must notify us immediately at <a href="mailto:support@soundcheckcapital.com">support@soundcheckcapital.com</a>.</p>

          <h3>Accuracy of and Changes to your Information</h3>
          <p>You agree to provide true, accurate, and complete profile and ticket sales information, banking and business information, information regarding your ticketing partners (the "Ticketing Partners") including such other information or credentials as may be prompted by any registration forms on the Site or otherwise requested by the Company for any other Ticketing Partners, including with respect to accounts maintained at any third-party sites. You further agree to provide such information, data, and materials as the Company may request to establish and/or verify your or any other person's identity (including any Guarantor, if applicable) or authority to enter into binding agreements on behalf of the business or entity, or to establish and/or verify the business or entity's legal existence, good standing in any jurisdiction and eligibility to use the Site or Services, or to establish and/or verify your eligibility for receiving potential financings from the Company's affiliates (collectively, the "Account Information and Diligence Materials"). You further agree to promptly update all your Account Information and Diligence Materials whenever the information provided to us is no longer accurate. If you do not do this, the accuracy and effectiveness of the Services provided to you will be affected, as well as your eligibility for any financings. If you need help in changing your information, please email us at <a href="mailto:support@soundcheckcapital.com">support@soundcheckcapital.com</a>. We are not responsible for any payment processing errors or fees or other Services-related issues arising from your failure to keep your Account Information and Diligence Materials current and accurate. You represent that you are a legal owner of, and that you are authorized to provide us with, all Account Information and Diligence Materials and other information necessary to facilitate your use of the Services, the Site and to apply for financings from the Company's affiliates.</p>
          <p>You agree to provide a valid and accurate EIN for your business and a valid and accurate Social Security Number for any beneficial owner(s) and you agree that the Company may use it to verify business and beneficial owner identities. You authorize the Company to make any inquiries we consider necessary to validate your identity. These inquiries may include asking you for further information, requiring you to provide your full address, your date of birth, your social security number and/or requiring you to take steps to confirm ownership of your email address or financial instruments, ordering a business credit report, or verifying information you provide against third-party databases or through other sources. If requested, you agree to provide documentation we may deem necessary in our sole discretion, to prove your relationship with any beneficial owner or other people on your account and that you are duly authorized to act on their behalf. In the event we do not receive all the required personal information during the enrollment process, you agree that we may, in our sole discretion, use our database, the database of our affiliates, or other resources to attempt to complete the required information on your behalf. In addition, in consideration of your use of the Site and the Service on behalf of a business or other entity member, you, individually and on behalf of such business or entity, agree to promptly notify the Company regarding any material changes to information or circumstances impacting the business or entity's legal existence, good standing in any jurisdiction in which the business or entity is authorized to conduct business, or eligibility for continued use of the Site or any Service.</p>

          <h3>Disclosure and Consent to Electronic Communications</h3>
          <p>You understand and agree that you are entering into these Terms of Service electronically and that certain categories of information ("Communications") may be provided by the Company to you by electronic means (i.e., via email, through the Service by displaying links to notices generally on the Site, or to your mobile device), unless and until you withdraw your consent as described below. The categories of Communications that may be provided by electronic means include:</p>
          <ul>
            <li>These Terms of Service and any amendments, modifications, or supplements;</li>
            <li>Records of any payment and other transactions you handle through the Sites or Services, including payment histories and transaction confirmations;</li>
            <li>Disclosures or notices provided in connection with the Services, including any required by federal or state law;</li>
            <li>Any customer service communications, including communications with respect to claims of error or unauthorized use of the Sites or Services; and</li>
            <li>Any other communication related to the Sites or Services.</li>
          </ul>
          <p>Although we reserve the right to provide Communications in paper format at any time, you agree that we are under no obligation to do so. All Communications in either electronic or paper format will be considered to be "in writing" under applicable law. You should print a paper copy of these Terms of Service and any Communication that is important to you and retain the copy for your records. By agreeing to the Terms of Service, you agree to receive electronically all documents, communications, notices, contracts, and agreements arising from or relating to your use of the Site and Service. If you do not wish to receive these Terms of Service or the Communications electronically, you may not use the Sites or Services.</p>
          <p>If you have opened an account with us and you wish to withdraw your consent to have Communications provided electronically, you must close your account by contacting <a href="mailto:support@soundcheckcapital.com">support@soundcheckcapital.com</a> and stop using the Sites and Services. Any withdrawal of your consent to receive electronic Communications will be effective only after we have a reasonable period of time to process your withdrawal and only after all amounts owing under any Advance Agreements, to the extent applicable, have been satisfied by you. We reserve the right, in our sole discretion, to discontinue the provision of your electronic Communications, or to terminate or change the terms and conditions on which we provide electronic Communications.</p>

          <h3>Services</h3>
          <p>The Company offers various tools and functions through the Sites including when you register, apply for business financings from our affiliates, access or use our website, mobile applications, products, network and services, or when you otherwise interact with us (collectively, the "Services").</p>

          <h3>Fees</h3>
          <p>There is no cost to maintain the Company account. The Services offered may require the payment of fees and other amounts, and are subject to separate Advance Agreements into which you must enter prior to participating in such Service and receive any financings from the Company's affiliates. Other Services offered from the Company may require one-time payments, on-going subscription payments, or other types of payments to access.</p>

          <h3>Your Use of the Services and the Business Financings</h3>
          <p>Your right to access and use the Site and use the Services is not transferable by you to any other person or entity, and you may only access and use the Sites and Services for lawful and proper purposes.</p>
          <p>In order to allow you to use certain Services, we may be required to verify your identity. You hereby authorize us to make any inquiries we consider necessary to validate your identity and to connect with all the necessary Ticketing Partners in order to conduct due diligence on you and your business as part of receiving the Services. These inquiries may include asking you for further information, requiring you to provide a taxpayer identification number, requiring you to take steps to confirm ownership of your email address or financial instruments, or verifying ticket sales and other information you provide and/or give us access to with your Ticketing Partners against third-party databases or through other sources. If you do not provide this information (including Account Information and Diligence Materials) or any other information requested, or if we cannot verify your identity or if we are not satisfied with the results (in our sole and absolute discretion), we can refuse to allow you to use the Services.</p>
          <p>The Services and financings are for business purposes only. You represent, warrant, and covenant that all financing proceeds received from the Company's affiliates are for business purposes only. You also represent, warrant, and covenant that no financing proceeds will be used for personal, household, family, or consumer purposes. You further understand and agree that you are not receiving a consumer extension of credit nor any type of consumer credit and that none of the statutory and regulatory protections for consumers will apply to you with respect to the Services, any financing or to our affiliates for extending the financing(s). You represent that the bank accounts used to receive financing funds and for automated submission payments due are used solely for business purposes and that the account(s) named are not, and will not, be used for personal, household, family, or consumer purposes.</p>
          <p>SoundCheck strongly encourages and advises you to seek counsel from a competent attorney and accountant to ensure the Services and the Company's affiliates' financing products meet your needs and that you have the ability to meet the obligations required of the Company's affiliates' financing(s). You further acknowledge that you have been advised to and have had the opportunity to seek legal and accounting advice prior to entering into any Advance Agreements.</p>
          <p>Your access and use of the Sites or Services may be interrupted from time to time for any of several reasons, including the malfunction of equipment, periodic updating, maintenance or repair of the Service, events beyond our control, or other actions that the Company, in its sole discretion, may elect to take. In no event will the Company be liable to any party for any loss, cost, or damage that results from any period of downtime of the Sites or Services. The provisions of this paragraph are in addition to, and not intended to limit or modify, the limitation of liability language or disclaimers otherwise contained in these Terms of Service.</p>

          <h3>Funds Distribution and Repayment Services – ACH Authorization Policy</h3>
          <p>In order to use the payment functionality of SoundCheck's application, you must open an account provided by SoundCheck's ACH processing provider and you must accept their terms of services and privacy policies as applicable. Any funds held in the ACH processors account are held by the ACH processor's financial institution partners as set out in their Terms of Service. You authorize us to collect and share with our ACH processor your personal information including full name, date of birth, social security number, physical address, email address and financial information, and you are responsible for the accuracy and completeness of that data. You understand that you will access and manage your ACH processor account through the SoundCheck application, and ACH account notifications will be sent by us, not the ACH processor. SoundCheck will provide customer support for your ACH account activity, and can be reached at <a href="https://www.soundcheckcapital.com" target="_blank" rel="noopener noreferrer">https://www.soundcheckcapital.com</a> or <a href="mailto:support@soundcheckcapital.com">support@soundcheckcapital.com</a>.</p>
          <p>You agree that in order to disconnect your financial institution from use for automated payments due to SoundCheck and its lending affiliates, you must first pay all outstanding amounts due. At such time, you may disconnect your financial institution from SoundCheck. You may also disconnect your financial institution from SoundCheck by canceling your SoundCheck account. Should SoundCheck be unable to connect to your financial institution for any reason while you have an outstanding financing balance, you shall be in breach of the Terms of Service and the Advance Agreements for your specific financings outstanding.</p>

          <h3>Modification to Site or Services</h3>
          <p>The Company further reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Sites or Services with or without notice. You agree that the Company shall not be liable to you or to any third party for any modification, suspensions, or discontinuance of the Sites or Services. The provisions of this paragraph are in addition to, and not intended to limit or modify, any limitation of liability or disclaimer language otherwise contained in these Terms of Service.</p>

          <h3>Rights you Grant to Us</h3>
          <p>By submitting information, materials and other content to the Company through the Service, you are licensing that content to the Company solely for the purpose of providing the Service. The Company may use and store the content for the purpose of providing the Service to you. By submitting this content to the Company, you represent that you are entitled to submit it to the Company for use for this purpose, without any obligation by the Company to pay any fees or other limitations. You are solely responsible for any and all data or information we collect from you or any third party (including Ticketing Partners) in connection with the use of the Services with the Company or any financing transaction with the Company's affiliates. As part of providing the Services, you acknowledge that accessing and/or using the Services will require the transmission of unencrypted information and data, and you bear the risk of loss of any such information or the potential exposure of such information and/or data.</p>
          <p>By using the Service, you expressly authorize the Company to access your Account Information and Diligence Materials maintained by Ticketing Partners and other identified third parties, on your behalf as your agent. You hereby authorize and permit the Company to use and store information submitted by you to the Service to accomplish the foregoing, to perform data gather so as to allow our affiliates to perform diligence and determine your eligibility for financings, and to configure the Service so that it is compatible with the third-party sites for which you submit your information. For purposes of these Terms of Service, and in connection with the Account Information and Diligence Materials, as part of the Service and Affiliate Services, you grant the Company a limited power of attorney, and appoint the Company as your attorney-in-fact and agent, to access third-party sites and any Ticketing Provider sites, retrieve, maintain, and use your information with the full power and authority to do and perform each thing necessary in connection with such activities, as you could do in person. YOU ACKNOWLEDGE AND AGREE THAT WHEN THE COMPANY IS ACCESSING AND RETRIEVING ACCOUNT INFORMATION AND DILIGENCE MATERIALS FROM THIRD-PARTY SITES AND YOUR TICKETING PARTNERS, THE COMPANY IS ACTING AS YOUR AGENT, AND NOT AS THE AGENT OF OR ON BEHALF OF THE THIRD PARTY. You understand and agree that the Service is not sponsored or endorsed by any third parties accessible through the Service. You expressly relieve us from any and all liability arising from your use of any third-party website or service. You agree that all of your Ticketing Partners and any other third party account providers shall be entitled to rely on the foregoing authorization, agency and power of attorney granted by you. You understand and agree that the Services are not endorsed or sponsored by any third party account providers accessible through the Services.</p>
          <p>By accepting these Terms of Service, you expressly consent to be contacted by us, our agents, representatives, affiliates, or anyone calling on our behalf for any and all purposes, at any telephone number, or physical or electronic address you provide or at which you may be reached. You agree we may contact you in any way, including SMS messages (including text messages), calls using prerecorded messages or artificial voice, and calls and messages delivered using auto telephone dialing system or an automatic texting system. Automated messages may be played when the telephone is answered, whether by you or someone else. In the event that an agent or representative calls, he or she may also leave a message on your answering machine, voice mail, or via text. You represent that you are permitted to receive calls at each of the telephone numbers you have provided to us. You agree to alert us whenever you stop using a particular telephone number.</p>
          <p>You are solely responsible for all data, information, feedback, suggestions, text, content and other materials that you upload, post, deliver, provide or otherwise transmit or store (hereafter "post(ing)") in connection with or relating to the Services ("Your Content"). The Company reserves the right to access your account in order to respond to your requests for technical support. By posting your Content on or through the Service, you hereby do and shall grant the Company a worldwide, non-exclusive, perpetual, irrevocable, royalty-free, fully paid, sublicensable and transferable license to use, modify, reproduce, distribute, display, publish and perform your Content in connection with the Service from the Company or any financing from the Company's affiliates. The Company has the right, but not the obligation, to monitor the Services or your Content.</p>
          <p>You understand that the operation of the Service, including your Content, may be unencrypted and involve (a) transmissions over various networks; (b) changes to conform and adapt to technical requirements of connecting networks or devices and (c) transmission to the Company's third-party vendors and hosting partners to provide the necessary hardware, software, networking, storage, and related technology required to operate and maintain the Service. Accordingly, you acknowledge that you bear sole responsibility for adequate security, protection and backup of your Content. The Company will have no liability to you for any unauthorized access or use of any of Your Content, or any corruption, deletion, destruction or loss of any of your Content.</p>
          <p>You understand that by agreeing to these terms while signing up for our app, you are providing 'written instructions' to SoundCheck Capital, LLC, and any lender to whom SoundCheck Capital, LLC forwards this application in connection with this application for commercial lending under the Fair Credit Reporting Act authorizing SoundCheck Capital, LLC, and any such lender to obtain information from your personal credit report or other information from Experian. You authorize SoundCheck Capital, LLC, and any such lender to obtain such information solely in connection with this application for commercial lending.</p>
          <p>The Company reserves the right to use your name and/or company name as a reference for marketing or promotional purposes on the Company's website and in other communication with existing or potential Company customers. To decline the Company this right you need to email <a href="mailto:support@soundcheckcapital.com">support@soundcheckcapital.com</a> stating that you do not wish to be used as a reference.</p>

          <h3>No Unlawful or Prohibited Use</h3>
          <p>As a condition of your use of the Sites and Services and entering into any financing transaction with the Company's affiliates, you represent and warrant to the Company that you will not use the Sites or Services for any purpose that is unlawful or prohibited by these Terms of Service.</p>
          <p>You agree that you will not:</p>
          <ul>
            <li>Sublicense, resell, rent, lease, transfer, assign, time share or otherwise commercially exploit or make the Service available to any third party;</li>
            <li>Use the Sites or Services in any manner that could damage, disable, overburden, or impair the Sites or Services;</li>
            <li>Obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the Sites or Services;</li>
            <li>Use the Service in any unlawful manner (including without limitation in violation of any data, privacy or export control laws) or in any manner that interferes with or disrupts the integrity or performance of the Service or its components;</li>
            <li>Modify, adapt or hack the Service to, or otherwise attempt to gain unauthorized access to the Service or its related systems or networks;</li>
            <li>Access the Sites by any means other than through the interface that is provided by the Company for use in accessing the Sites;</li>
            <li>Use or attempt to use any engine, software, tool, agent, or other device or mechanism to navigate or search the Site or Services or attempt to decipher, decompile, disassemble, or reverse-engineer any of the software comprising or in any way making up a part of the Site or the Service;</li>
            <li>Frame the Site, utilize framing techniques to enclose any content or other proprietary information, place pop-up windows over the Site's pages, or otherwise affect the display of the Site's pages;</li>
            <li>Engage in the practices of "screen scraping," "database scraping" or any other activity with the purpose of obtaining content or other information;</li>
            <li>Register for multiple accounts on behalf of the same business or entity; or</li>
            <li>Use data provided by the Company in any manner whatsoever for any competing uses or purposes.</li>
          </ul>
          <p>All rights, title and interest in and to the Service and its components will remain with and belong exclusively to the Company. You shall comply with any codes of conduct, policies or other notices the Company provides you or publishes in connection with the Service, and you shall promptly notify the Company if you learn of a security breach related to the Service.</p>
          <p>If the Company, in its sole discretion, believes that you may have engaged in any activities restricted by these Terms of Service or by law, we may (in our sole and absolute discretion) take various actions to protect the Company, other users, and other third parties (including any Ticketing Partners) from fees, fines, penalties, and any other liability (with or without notice), including:</p>
          <ul>
            <li>We may close, suspend, or limit your access to your account or ability to use the Sites or Services;</li>
            <li>We may update inaccurate information you provided us;</li>
            <li>We may refuse to allow you to use the Sites or Services in the future;</li>
            <li>We may take legal action against you; and</li>
            <li>We may hold you liable to the Company for the amount of the Company's damages caused by your violation of these Terms of Service.</li>
          </ul>
          <p>The Company, in its sole and absolute discretion, reserves the right to terminate these Terms of Service, access to its Sites or the Sites of its affiliates, or access to the Services or the Services of its Affiliates for any reason and at any time with or without notice to you.</p>

          <h3>Company's Intellectual Property Rights</h3>
          <p>All content included or available in connection with the Sites, including any and all materials, information, text, data, software, contents, names, trade names, trademarks, trade dress, service marks, layout, logos, designs, images, graphics, illustrations, artwork, icons, photographs, displays, sound, music, video, animation, organization, assembly, arrangement, interfaces, databases, technology, and all intellectual property of any kind whatsoever (collectively, the "Content") and the selection and arrangement thereof is owned exclusively by the Company or the licensors or suppliers of the Company and is protected by U.S. and international copyright and other intellectual property laws. All rights are hereby reserved. Without limiting the foregoing, no Content on the Sites may be copied, reproduced, duplicated, published, or distributed in any form or by any means whatsoever without the express prior written permission of the Company or the appropriate licensor or supplier.</p>
          <p>Any feedback, questions, comments, suggestions, ideas, or the like that you send to the Company will be treated as being non-confidential and nonproprietary, and the Company will be free to use such information for any purpose whatsoever including developing, manufacturing, and marketing products and services incorporating the information.</p>

          <h3>Disclaimer of Representations and Warranties</h3>
          <p>THE SITES, THE SERVICES, INFORMATION, DATA, FEATURES, AND ALL CONTENT IS OFFERED AND MADE AVAILABLE ON AN "AS IS, WHERE IS" AND "AS AVAILABLE" BASIS. THE COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE CONTENT OR OPERATION OF THE SITES OR THE SERVICES. YOU EXPRESSLY AGREE THAT YOUR USE OF THE SITES AND THE SERVICES IS AT YOUR SOLE RISK.</p>
          <p>THE COMPANY MAKES NO REPRESENTATIONS, WARRANTIES OR GUARANTEES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, OR CONTINUED AVAILABILITY OF THE CONTENT ON THE SITES OR THE SERVICES, AND EXPRESSLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. THE COMPANY MAKES NO REPRESENTATION, WARRANTY, OR GUARANTEE THAT THE CONTENT THAT MAY BE AVAILABLE THROUGH THE SITES OR THE SERVICES IS FREE OF BUGS, DEFECTS, OR ERRORS, OR INFECTION FROM ANY VIRUSES OR OTHER CODE OR COMPUTER PROGRAMMING ROUTINES THAT CONTAIN CONTAMINATING OR DESTRUCTIVE PROPERTIES OR THAT ARE INTENDED TO DAMAGE, SURREPTITIOUSLY INTERCEPT, OR EXPROPRIATE ANY SYSTEM, DATA, OR PERSONAL INFORMATION.</p>
          <p>THE SERVICE IS NOT INTENDED TO PROVIDE LEGAL, TAX, OR FINANCIAL ADVICE. THE COMPANY IS NOT A FINANCIAL PLANNER, BROKER, OR TAX ADVISOR. Before making any final decisions or entering into any financing transaction with the Company's affiliates, you should consider obtaining additional information and advice from your attorney, accountant or other financial or legal advisers who are fully aware of your entity's circumstances. The Company does not assume any responsibility for the timeliness, accuracy, deletion, non-delivery, or failure to store Account Information and Diligence Materials. Any information made available through the Services will only reflect the information that we most recently accessed, and as such, may not reflect activity that occurred after we last accessed the applicable third-party site or any pending transactions.</p>
          <p>You understand and agree that any alerts provided to you through the Services may be delayed or prevented by a variety of factors. The Company makes commercially reasonable efforts to provide alerts in a timely manner with accurate information, but we cannot guarantee the delivery, timeliness, or accuracy of the content of any alert. The Company shall not be liable for any delays, failure to deliver, or misdirected delivery of any alert; for any errors in the content of an alert; or for any actions taken or not taken by you or any third party in reliance on an alert.</p>

          <h3>Limitation of Liability</h3>
          <p>IN NO EVENT WILL WE BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, EXEMPLARY, LIQUIDATED, PUNITIVE OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, LOST PROFITS OR BUSINESS, LOSS OF USE, LOSS OF DATA, BUSINESS INTERRUPTION, TEMPORARY INTERRUPTIONS IN SERVICES (INCLUDING IF WE ARE UNABLE TO COMPLETE A TRANSACTION), LOSS OF BUSINESS REPUTATION, LATE PENALTIES, LATE PAYMENTS TO THIRD PARTIES, CANCELLATION OF THIRD PARTY CONTRACTS OR LOSS OF GOODWILL), OR THE COSTS OF PROCURING SUBSTITUTE SERVICES OR PRODUCTS, ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF SERVICE, THE SITES, THE SERVICES, YOUR USE THEREOF, OR ANY OF THE USER SUBMISSIONS, INFORMATION, DATA, OR OTHER MATERIAL TRANSMITTED THROUGH OR RESIDING ON THE SITES, OR ANY ERRORS, DEFECTS, INTERRUPTIONS, DELETIONS, OR LOSSES RESULTING THEREFROM WHETHER SUCH LIABILITY ARISES FROM ANY CLAIM BASED UPON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE, AND WHETHER OR NOT IT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. UNLESS OTHERWISE EXPRESSLY SET FORTH IN THESE TERMS OF SERVICE, OUR LIABILITY TO YOU FOR ANY CAUSE WHATEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO $500.00 (FIVE HUNDRED DOLLARS). YOU ACKNOWLEDGE THAT IF NO FEES HAVE BEEN PAID TO US IN CONNECTION WITH THESE TERMS OF SERVICE, YOU WILL BE LIMITED TO INJUNCTIVE RELIEF ONLY, UNLESS OTHERWISE PERMITTED BY LAW, AND WILL NOT BE ENTITLED TO DAMAGES OF ANY KIND FROM US, REGARDLESS OF THE CAUSE OF ACTION.</p>
          <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. IN SUCH STATES LIABILITY IS LIMITED TO THE EXTENT PERMITTED BY LAW. WE DO NOT REPRESENT OR WARRANT THAT ANY OF OUR SITE OR SERVICES WILL BE UNINTERRUPTED OR ENTIRELY ERROR FREE.</p>
          <p>We do not have any fiduciary or other special relationship to you or any of your stockholders, equity holders, debt holders or affiliates. We have not assumed an advisory or fiduciary responsibility in your favor or any of your stockholders or affiliates. You acknowledge and agree that you have consulted your own legal, tax and financial advisors to the extent you deem appropriate and that you are responsible for making your own independent judgment with respect to this transaction and the process leading thereto. You agree that you will not claim that we have rendered advisory services of any nature or owe a fiduciary or similar duty to you.</p>

          <h3>Indemnification of Company</h3>
          <p>You will defend, indemnify and hold us harmless, including our officers, directors, shareholders, members, equity holders, affiliates and employees, from and against all claims, actions, damages, obligations, costs, demands and expenses, including but not limited to attorney's fees, in whole or in part arising out of or attributable to any breach of these Terms of Service by you, any of your Content, your violation of any third party right, or your other access, contribution to, use or misuse of the Service. We will provide notice to you of any such claim, suit or demand. We reserve the right to assume the exclusive defense and control of any matter which is subject to indemnification under this section. In such case, you agree to cooperate with any reasonable requests assisting our defense of such matter.</p>

          <h3>Governing Law; Jury Trial and Class Action Waiver</h3>
          <p>These Terms of Service, and your relationship with the Company under these Terms of Service, is be governed by, and will be construed in accordance with, the internal laws of the State of Delaware, without regard to principles of conflict of laws. You hereby irrevocably submit to the exclusive jurisdiction of any state or federal court sitting in Los Angeles County, California for any and all disputes regarding these Terms of Use or the relationship of the parties. You understand that, in return for agreement to these provisions, the Company is able to offer the Service at the terms designated, and that your assent to these provisions is an indispensable consideration to these Terms of Service.</p>
          <p>YOU WAIVE THE RIGHT TO A TRIAL BY JURY IN ANY SUIT, ACTION OR PROCEEDING ON ANY MATTER ARISING IN CONNECTION WITH OR IN ANY WAY RELATED TO, THESE TERMS OF SERVICE, THE TRANSACTIONS CONTEMPLATED BY THESE TERMS OF SERVICE, OR THE ENFORCEMENT OF THESE TERMS OF SERVICE, EXCEPT WHERE SUCH WAIVER IS PROHIBITED BY LAW. YOU ACKNOWLEDGE THAT YOU MAKE THIS WAIVER KNOWINGLY, WILLINGLY, VOLUNTARILY AND WITHOUT DURESS, AND ONLY AFTER BEING PROVIDED WITH THE OPPORTUNITY TO CONSIDER THE RAMIFICATIONS OF THIS WAIVER WITH YOUR ATTORNEYS.</p>
          <p>YOU WAIVE ANY RIGHT TO ASSERT ANY CLAIMS AGAINST THE COMPANY, ITS PARENT COMPANIES, AFFILIATES, SUBSIDIARIES, PREDECESSORS, SUCCESSORS, ASSIGNS, AGENTS, CONTRACTORS, EMPLOYEES, OFFICERS, DIRECTORS OR REPRESENTATIVES, AS A REPRESENTATIVE OR MEMBER OF ANY CLASS OR IN ANY OTHER REPRESENTATIVE ACTION, EXCEPT WHERE SUCH WAIVER IS PROHIBITED BY LAW. TO THE EXTENT THIS PROVISION ALLOWS YOU TO PROCEED WITH A CLASS OR REPRESENTATIVE ACTION AGAINST THE COMPANY, YOU AGREE THAT THE PREVAILING PARTY WILL NOT BE ENTITLED TO RECOVER ATTORNEY'S FEES OR COSTS ASSOCIATED WITH PURSUING THE CLASS OR REPRESENTATIVE ACTION (NOTWITHSTANDING ANY OTHER PROVISION IN THESE TERMS OF SERVICE).</p>
          <p>YOU AND THE COMPANY AGREE THAT, ABSENT A WRITTEN AGREEMENT BETWEEN THE PARTIES ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SITE MUST BE FILED WITHIN ONE MONTH AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION SHALL BE PERMANENTLY BARRED.</p>

          <h3>Error Resolution</h3>
          <p>If you believe that there has been an error made on your account, contact us by emailing <a href="mailto:support@soundcheckcapital.com">support@soundcheckcapital.com</a>.</p>
          <ul>
            <li>If you believe a transaction receipt or a statement is wrong.</li>
            <li>If you need more information about a transaction on the receipt or statement.</li>
          </ul>
          <p>We must hear from you within one (1) business day of us sending you a receipt.</p>
          <p>Your inquiry must include:</p>
          <ul>
            <li>Your name, email associated with your account, and your account number (if available);</li>
            <li>A description of the error or the transaction you are unsure about;</li>
            <li>A clear explanation of why you believe there is an error or why you need more information;</li>
            <li>The dollar amount of the suspected error.</li>
          </ul>
          <p>If you tell us orally, we may require that you send us your inquiry via email within ten (10) business days.</p>

          <h3>Miscellaneous</h3>
          <p>If any portion of these Terms of Service is deemed unlawful, void or unenforceable by a court of competent jurisdiction, these Terms of Service as a whole shall not be deemed unlawful, void or unenforceable, but only that portion of these Terms of Service that is unlawful, void or unenforceable shall be stricken from these Terms of Service.</p>
          <p>You agree that if the Company does not exercise or enforce any legal right or remedy which is contained in these Terms of Service (or which the Company has the benefit of under any applicable law), this will not be taken to be a formal waiver of the Company's rights and that those rights or remedies will still be available to the Company.</p>
          <p>All covenants, agreements, indemnifications, limitations on liability, representations and warranties made in these Terms of Service shall survive your acceptance of these Terms of Service and the termination of these Terms of Service.</p>
          <p>The Company uses third parties to gather your data from financial institutions. By using our Service, you grant our third-party provider the right, power, and authority to act on your behalf to access and transmit your personal and financial information from the relevant financial institution according to terms of our third-party provider's privacy policy and to order any reports or searches.</p>
          <p>You may not assign this Terms of Service without the prior written consent of the Company, but the Company may assign or transfer this Terms of Service, in whole or in part, without restriction.</p>

          <h3>Contact Us</h3>
          <p>In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at <a href="mailto:support@soundcheckcapital.com">support@soundcheckcapital.com</a>.</p>
        </div>
      </div>
    </div>
  )
}
